import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-gray-100 font-sans min-h-screen">
        <header className="bg-black text-white">
          <div className="container mx-auto px-4 py-3 flex items-center justify-between">
            <div className="flex items-center space-x-4">
              <div className="text-yellow-500 font-bold text-lg">IMDb</div>
              {/* ...existing code... */}
            </div>
            <div className="flex items-center space-x-4">
              <input
                type="text"
                placeholder="Search IMDb"
                className="bg-gray-800 text-sm text-white px-3 py-1 rounded focus:outline-none"
              />
              {/* ...existing code... */}
            </div>
          </div>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
